Repository prolic/HumusAmqp, pull requests merged in 2020-03, with the labels that each got.

#88 PHPUnit 8
  .travis.yml
  composer.json
  tests/AbstractChannelRecoverTest.php
  tests/AbstractChannelTest.php
  tests/AbstractExchangeTest.php
  tests/AbstractJsonProducerTest.php
  tests/AbstractPlainProducerTest.php
  tests/AbstractQueueTest.php
  tests/AmqpExtension/ChannelRecoverTest.php
  tests/AmqpExtension/ChannelTest.php
  tests/AmqpExtension/ConnectionTest.php
  tests/AmqpExtension/ExchangeTest.php
  tests/AmqpExtension/JsonProducerTest.php
  tests/AmqpExtension/PlainProducerTest.php
  tests/AmqpExtension/QueueTest.php
  tests/Helper/DeleteOnTearDownTrait.php
  tests/JsonRpc/AbstractJsonRpcClientAndServerTest.php
Labels: enhancement

#84 php-amqplib 2.9 support
  README.md
  composer.json
  docs/articles/getting_started.rst
  docs/index.rst
  phpunit.xml.dist
  src/Driver/PhpAmqpLib/Channel.php
  src/Driver/PhpAmqpLib/Envelope.php
  src/Driver/PhpAmqpLib/Queue.php
  src/Driver/PhpAmqpLib/SocketConnection.php
  tests/AbstractChannelRecoverTest.php
  tests/AbstractChannelTest.php
  tests/AbstractExchangeTest.php
  tests/AbstractQueueTest.php
  tests/AmqpExtension/QueueTest.php
  tests/JsonRpc/AbstractJsonRpcClientAndServerTest.php
  tests/PhpAmqpLib/QueueTest.php
  tests/PhpAmqpLib/SslConnectionTest.php
  tests/PhpAmqpLib/StreamConnectionTest.php
Labels: bug, enhancement

#91 Json rpc error
  src/JsonRpc/Error.php
  src/JsonRpc/JsonRpcClient.php
  src/JsonRpc/JsonRpcError.php
  src/JsonRpc/JsonRpcResponse.php
  src/JsonRpc/JsonRpcServer.php
  src/JsonRpc/Response.php
  tests/JsonRpc/AbstractJsonRpcClientAndServerTest.php
  tests/JsonRpc/ResponseTest.php
Labels: BC break, enhancement
